"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
  let g:vundles=['general', 'programming', 'git', 'ruby', 'completion', 'misc', 'javascript', 'html']
  let g:neocomplcache_enable_at_startup = 1

  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  Plugin 'tpope/vim-commentary'
  Plugin 'kien/rainbow_parentheses'

  call vundle#end()            " required
  filetype plugin indent on    " required
endif

" Customize to your needs...

