#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# add-apt-repository
###############################################################################

if [[ -f $DIR/sources/apt ]]; then
  exec<$DIR/sources/apt
  while read line
  do
    if [[ ! "$source" =~ (^#|^$) ]]; then
      sudo add-apt-repository -y $source
    fi
  done
fi

sudo apt-get update

###############################################################################
# apt-get
###############################################################################

if [[ -f $DIR/packages/apt ]]; then
  exec<$DIR/packages/apt
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      packages="$packages $line"
    fi
  done
  sudo apt-get install -y $packages
fi

## rvm
echo "Installing RVM"
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
bash -s stable < $(curl -sSL https://get.rvm.io)
echo "Done"
##

