#!/usr/bin/env bash

# Path to the bash it configuration
export BASH_IT="/home/christianblunden/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='zork'
# export TERM=xterm-256color
test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

export PROJECT_PATHS=~/code:~/code/uswitch
export LOCAL_IP=$(ip route get 8.8.8.8 | awk '{print $NF; exit}')
export GOPATH=$HOME/code/gopath

# Load Bash It
source $BASH_IT/bash_it.sh

source $HOME/.bash_path

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# The next line updates PATH for the Google Cloud SDK.
source '/home/christianblunden/code/google-cloud-sdk/path.bash.inc'

# The next line enables shell command completion for gcloud.
source '/home/christianblunden/code/google-cloud-sdk/completion.bash.inc'
